name: Run Tests

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**/*'
      - 'tests/**/*'
      - 'package*.json'
      - 'tsconfig.json'
      - 'jest.config.js'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**/*'
      - 'tests/**/*'
      - 'package*.json'
      - 'tsconfig.json'
      - 'jest.config.js'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - run: npm run compile
      - run: npm run test
